### ISSUE TITLE
Create a migrate submodule

### ISSUE THREAD

**Issue by imanoleguskiza** [nuvoleweb/integration#2]
All the functionality regarding the migration of json files should be repackaged in a separate submodule.

**Comment by ademarco** [comment]
This is an interesting proposal, we should consider the following points (let's imagine the new module is called `integration_migrate`):
1. At the moment Consumer plugins depend on Migrate, this might change in the future but for the time being this is the situation which will make `integration_migrate` a new dependency for the whole stack. I don't have any problem with this.
2. `integration_migrate` will need to depend from `integration` module since the `Document` class is namespaced with `Drupal\integration`. This means that we will always have Backend classes available, that's not a burden though, if you don't enable the UI modules you don't see anything. We could also put backend-related code into a separate module but that's not really necessary at the moment.
3. Ideally all classes namespaced `Drupal\integration_consumer\Migrate` (except for `MigrateSourceBackend`) will become part of the new module, so the namespace will arguably change into `Drupal\integration_migrate`.
4. Tests need to be adapted as well, I would create a new directory, called `tests/Migrate` and move `integration_test` module (which is only used to test migration) and what's contained under `tests/Consumer/Migrate` into the new directory, taking care of updating the namespace.

Alternatively we can just move all migration-related code in the `integration` module, since that module will always need to be enabled, so we would not need to create a new module at all.

Looking forward to your thoughts on this.

**Comment by imanoleguskiza** [comment]
If I'm not mistaken and we create the `integration_migrate` module, this will only contain the classes under `Drupal\integration_consumer\Migrate` and nothing else, so it might be a better idea to move the code directly into the `integration` module as you mention.

**Comment by ademarco** [comment]
Yes that would be ideal indeed!

**Comment by ademarco** [comment]
I see some work has already been done on https://github.com/imanoleguskiza/integration/tree/development that's great! Make sure you git-rebase it asap on the latest commit since quite a lot has been changed since. Do you need me to review it already or you prefer to wait a little more?

**Comment by imanoleguskiza** [comment]
Hi Antonio,
let me rebase it and then we can review it if you want :)

**Comment by ademarco** [comment]
Perfect!

**Comment by ademarco** [comment]
So at the end I've created a module called `integration_migrate` and placed all stand-alone Migrate components within it.

The main reason for this is that now if we just need to import JSON files we only enable `integration_migrate`, which only depends on migrate and registry_autoload:

```
$ drush en integration_migrate
The following extensions will be enabled: integration_migrate, registry_autoload, migrate
Do you really want to continue? (y/n): 
```

If we would have put Migrate components in the main Integration module then a site that only needed the producer plugin to export content would have also the Migrate module enabled, which is kind of cumbersome.

**Comment by ademarco** [comment]
Documentation updated at https://github.com/nuvoleweb/integration/wiki/6.-Stand-alone-migrations
